// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor;

import com.azure.ai.metricsadvisor.administration.models.DataFeed;
import com.azure.ai.metricsadvisor.administration.models.DataFeedGranularity;
import com.azure.ai.metricsadvisor.administration.models.DataFeedIngestionSettings;
import com.azure.ai.metricsadvisor.administration.models.DataFeedMissingDataPointFillSettings;
import com.azure.ai.metricsadvisor.administration.models.DataFeedOptions;
import com.azure.ai.metricsadvisor.administration.models.DataFeedRollupSettings;
import com.azure.ai.metricsadvisor.administration.models.DataFeedSchema;
import com.azure.ai.metricsadvisor.implementation.MetricsAdvisorAdministrationsImpl;
import com.azure.ai.metricsadvisor.implementation.models.DataFeedDetail;
import com.azure.ai.metricsadvisor.implementation.models.FillMissingPointType;
import com.azure.ai.metricsadvisor.implementation.models.Granularity;
import com.azure.ai.metricsadvisor.implementation.models.NeedRollupEnum;
import com.azure.ai.metricsadvisor.implementation.models.RollUpMethod;
import com.azure.ai.metricsadvisor.implementation.models.ViewMode;
import com.azure.ai.metricsadvisor.implementation.util.DataFeedTransforms;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.PagedFlux;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.BinaryData;
import com.azure.core.util.Context;
import com.azure.core.util.FluxUtil;
import com.azure.core.util.logging.ClientLogger;
import reactor.core.publisher.Mono;

import java.util.Objects;
import java.util.UUID;

import static com.azure.ai.metricsadvisor.administration.models.DataFeedGranularityType.CUSTOM;
import static com.azure.ai.metricsadvisor.implementation.util.Utility.parseOperationId;
import static com.azure.core.util.FluxUtil.monoError;
import static com.azure.core.util.FluxUtil.withContext;
import static com.azure.core.util.tracing.Tracer.AZ_TRACING_NAMESPACE_KEY;

/** Initializes a new instance of the asynchronous MetricsAdvisorClient type. */
@ServiceClient(builder = MetricsAdvisorAdministrationClientBuilder.class, isAsync = true)
public final class MetricsAdvisorAdministrationAsyncClient {
    @Generated private final MetricsAdvisorAdministrationsImpl serviceClient;

    private final ClientLogger logger =
            new ClientLogger(com.azure.ai.metricsadvisor.MetricsAdvisorAdministrationAsyncClient.class);

    /**
     * Initializes an instance of MetricsAdvisorAdministrationAsyncClient class.
     *
     * @param serviceClient the service client implementation.
     */
    @Generated
    MetricsAdvisorAdministrationAsyncClient(MetricsAdvisorAdministrationsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Update anomaly alerting configuration.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     name: String
     *     description: String
     *     crossMetricsOperator: String(AND/OR/XOR)
     *     splitAlertByDimensions: [
     *         String
     *     ]
     *     hookIds: [
     *         String
     *     ]
     *     metricAlertingConfigurations: [
     *         {
     *             anomalyDetectionConfigurationId: String
     *             anomalyScopeType: String(All/Dimension/TopN)
     *             negationOperation: Boolean
     *             dimensionAnomalyScope: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             topNAnomalyScope: {
     *                 top: int
     *                 period: int
     *                 minTopCount: int
     *             }
     *             severityFilter: {
     *                 minAlertSeverity: String(Low/Medium/High)
     *                 maxAlertSeverity: String(Low/Medium/High)
     *             }
     *             snoozeFilter: {
     *                 autoSnooze: int
     *                 snoozeScope: String(Metric/Series)
     *                 onlyForSuccessive: boolean
     *             }
     *             valueFilter: {
     *                 lower: Double
     *                 upper: Double
     *                 direction: String(Both/Down/Up)
     *                 type: String(Value/Mean)
     *                 metricId: String
     *                 triggerForMissing: Boolean
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     anomalyAlertingConfigurationId: String
     *     name: String
     *     description: String
     *     crossMetricsOperator: String(AND/OR/XOR)
     *     splitAlertByDimensions: [
     *         String
     *     ]
     *     hookIds: [
     *         String
     *     ]
     *     metricAlertingConfigurations: [
     *         {
     *             anomalyDetectionConfigurationId: String
     *             anomalyScopeType: String(All/Dimension/TopN)
     *             negationOperation: Boolean
     *             dimensionAnomalyScope: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             topNAnomalyScope: {
     *                 top: int
     *                 period: int
     *                 minTopCount: int
     *             }
     *             severityFilter: {
     *                 minAlertSeverity: String(Low/Medium/High)
     *                 maxAlertSeverity: String(Low/Medium/High)
     *             }
     *             snoozeFilter: {
     *                 autoSnooze: int
     *                 snoozeScope: String(Metric/Series)
     *                 onlyForSuccessive: boolean
     *             }
     *             valueFilter: {
     *                 lower: Double
     *                 upper: Double
     *                 direction: String(Both/Down/Up)
     *                 type: String(Value/Mean)
     *                 metricId: String
     *                 triggerForMissing: Boolean
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly alerting configuration unique id.
     * @param body anomaly alerting configuration.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> updateAnomalyAlertingConfigurationWithResponse(
            String configurationId, BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.updateAnomalyAlertingConfigurationWithResponseAsync(
                configurationId, body, requestOptions);
    }

    /**
     * Delete anomaly alerting configuration.
     *
     * @param configurationId anomaly alerting configuration unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> deleteAnomalyAlertingConfigurationWithResponse(
            String configurationId, RequestOptions requestOptions) {
        return this.serviceClient.deleteAnomalyAlertingConfigurationWithResponseAsync(configurationId, requestOptions);
    }

    /**
     * Create anomaly alerting configuration.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     anomalyAlertingConfigurationId: String
     *     name: String
     *     description: String
     *     crossMetricsOperator: String(AND/OR/XOR)
     *     splitAlertByDimensions: [
     *         String
     *     ]
     *     hookIds: [
     *         String
     *     ]
     *     metricAlertingConfigurations: [
     *         {
     *             anomalyDetectionConfigurationId: String
     *             anomalyScopeType: String(All/Dimension/TopN)
     *             negationOperation: Boolean
     *             dimensionAnomalyScope: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             topNAnomalyScope: {
     *                 top: int
     *                 period: int
     *                 minTopCount: int
     *             }
     *             severityFilter: {
     *                 minAlertSeverity: String(Low/Medium/High)
     *                 maxAlertSeverity: String(Low/Medium/High)
     *             }
     *             snoozeFilter: {
     *                 autoSnooze: int
     *                 snoozeScope: String(Metric/Series)
     *                 onlyForSuccessive: boolean
     *             }
     *             valueFilter: {
     *                 lower: Double
     *                 upper: Double
     *                 direction: String(Both/Down/Up)
     *                 type: String(Value/Mean)
     *                 metricId: String
     *                 triggerForMissing: Boolean
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param body anomaly alerting configuration.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> createAnomalyAlertingConfigurationWithResponse(
            BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.createAnomalyAlertingConfigurationWithResponseAsync(body, requestOptions);
    }

    /**
     * Query a single anomaly detection configuration.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     anomalyDetectionConfigurationId: String
     *     name: String
     *     description: String
     *     metricId: String
     *     wholeMetricConfiguration: {
     *         conditionOperator: String(AND/OR)
     *         smartDetectionCondition: {
     *             sensitivity: double
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: {
     *                 minNumber: int
     *                 minRatio: double
     *             }
     *         }
     *         hardThresholdCondition: {
     *             lowerBound: Double
     *             upperBound: Double
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: (recursive schema, see suppressCondition above)
     *         }
     *         changeThresholdCondition: {
     *             changePercentage: double
     *             shiftPoint: int
     *             withinRange: boolean
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: (recursive schema, see suppressCondition above)
     *         }
     *     }
     *     dimensionGroupOverrideConfigurations: [
     *         {
     *             group: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             conditionOperator: String(AND/OR)
     *             smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *             hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *             changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *         }
     *     ]
     *     seriesOverrideConfigurations: [
     *         {
     *             series: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             conditionOperator: String(AND/OR)
     *             smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *             hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *             changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> getAnomalyDetectionConfigurationWithResponse(
            String configurationId, RequestOptions requestOptions) {
        return this.serviceClient.getAnomalyDetectionConfigurationWithResponseAsync(configurationId, requestOptions);
    }

    /**
     * Update anomaly detection configuration.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     name: String
     *     description: String
     *     wholeMetricConfiguration: {
     *         conditionOperator: String(AND/OR)
     *         smartDetectionCondition: {
     *             sensitivity: Double
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: {
     *                 minNumber: Integer
     *                 minRatio: Double
     *             }
     *         }
     *         hardThresholdCondition: {
     *             lowerBound: Double
     *             upperBound: Double
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: (recursive schema, see suppressCondition above)
     *         }
     *         changeThresholdCondition: {
     *             changePercentage: Double
     *             shiftPoint: Integer
     *             withinRange: Boolean
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: (recursive schema, see suppressCondition above)
     *         }
     *     }
     *     dimensionGroupOverrideConfigurations: [
     *         {
     *             group: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             conditionOperator: String(AND/OR)
     *             smartDetectionCondition: {
     *                 sensitivity: double
     *                 anomalyDetectorDirection: String(Both/Down/Up)
     *                 suppressCondition: {
     *                     minNumber: int
     *                     minRatio: double
     *                 }
     *             }
     *             hardThresholdCondition: {
     *                 lowerBound: Double
     *                 upperBound: Double
     *                 anomalyDetectorDirection: String(Both/Down/Up)
     *                 suppressCondition: (recursive schema, see suppressCondition above)
     *             }
     *             changeThresholdCondition: {
     *                 changePercentage: double
     *                 shiftPoint: int
     *                 withinRange: boolean
     *                 anomalyDetectorDirection: String(Both/Down/Up)
     *                 suppressCondition: (recursive schema, see suppressCondition above)
     *             }
     *         }
     *     ]
     *     seriesOverrideConfigurations: [
     *         {
     *             series: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             conditionOperator: String(AND/OR)
     *             smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *             hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *             changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *         }
     *     ]
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     anomalyDetectionConfigurationId: String
     *     name: String
     *     description: String
     *     metricId: String
     *     wholeMetricConfiguration: {
     *         conditionOperator: String(AND/OR)
     *         smartDetectionCondition: {
     *             sensitivity: double
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: {
     *                 minNumber: int
     *                 minRatio: double
     *             }
     *         }
     *         hardThresholdCondition: {
     *             lowerBound: Double
     *             upperBound: Double
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: (recursive schema, see suppressCondition above)
     *         }
     *         changeThresholdCondition: {
     *             changePercentage: double
     *             shiftPoint: int
     *             withinRange: boolean
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: (recursive schema, see suppressCondition above)
     *         }
     *     }
     *     dimensionGroupOverrideConfigurations: [
     *         {
     *             group: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             conditionOperator: String(AND/OR)
     *             smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *             hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *             changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *         }
     *     ]
     *     seriesOverrideConfigurations: [
     *         {
     *             series: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             conditionOperator: String(AND/OR)
     *             smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *             hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *             changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param body anomaly detection configuration.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> updateAnomalyDetectionConfigurationWithResponse(
            String configurationId, BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.updateAnomalyDetectionConfigurationWithResponseAsync(
                configurationId, body, requestOptions);
    }

    /**
     * Delete anomaly detection configuration.
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> deleteAnomalyDetectionConfigurationWithResponse(
            String configurationId, RequestOptions requestOptions) {
        return this.serviceClient.deleteAnomalyDetectionConfigurationWithResponseAsync(configurationId, requestOptions);
    }

    /**
     * Create anomaly detection configuration.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     anomalyDetectionConfigurationId: String
     *     name: String
     *     description: String
     *     metricId: String
     *     wholeMetricConfiguration: {
     *         conditionOperator: String(AND/OR)
     *         smartDetectionCondition: {
     *             sensitivity: double
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: {
     *                 minNumber: int
     *                 minRatio: double
     *             }
     *         }
     *         hardThresholdCondition: {
     *             lowerBound: Double
     *             upperBound: Double
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: (recursive schema, see suppressCondition above)
     *         }
     *         changeThresholdCondition: {
     *             changePercentage: double
     *             shiftPoint: int
     *             withinRange: boolean
     *             anomalyDetectorDirection: String(Both/Down/Up)
     *             suppressCondition: (recursive schema, see suppressCondition above)
     *         }
     *     }
     *     dimensionGroupOverrideConfigurations: [
     *         {
     *             group: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             conditionOperator: String(AND/OR)
     *             smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *             hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *             changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *         }
     *     ]
     *     seriesOverrideConfigurations: [
     *         {
     *             series: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             conditionOperator: String(AND/OR)
     *             smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *             hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *             changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param body anomaly detection configuration.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> createAnomalyDetectionConfigurationWithResponse(
            BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.createAnomalyDetectionConfigurationWithResponseAsync(body, requestOptions);
    }

    /**
     * List all anomaly alerting configurations for specific anomaly detection configuration.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     value: [
     *         {
     *             anomalyAlertingConfigurationId: String
     *             name: String
     *             description: String
     *             crossMetricsOperator: String(AND/OR/XOR)
     *             splitAlertByDimensions: [
     *                 String
     *             ]
     *             hookIds: [
     *                 String
     *             ]
     *             metricAlertingConfigurations: [
     *                 {
     *                     anomalyDetectionConfigurationId: String
     *                     anomalyScopeType: String(All/Dimension/TopN)
     *                     negationOperation: Boolean
     *                     dimensionAnomalyScope: {
     *                         dimension: {
     *                             String: String
     *                         }
     *                     }
     *                     topNAnomalyScope: {
     *                         top: int
     *                         period: int
     *                         minTopCount: int
     *                     }
     *                     severityFilter: {
     *                         minAlertSeverity: String(Low/Medium/High)
     *                         maxAlertSeverity: String(Low/Medium/High)
     *                     }
     *                     snoozeFilter: {
     *                         autoSnooze: int
     *                         snoozeScope: String(Metric/Series)
     *                         onlyForSuccessive: boolean
     *                     }
     *                     valueFilter: {
     *                         lower: Double
     *                         upper: Double
     *                         direction: String(Both/Down/Up)
     *                         type: String(Value/Mean)
     *                         metricId: String
     *                         triggerForMissing: Boolean
     *                     }
     *                 }
     *             ]
     *         }
     *     ]
     *     nextLink: String
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedFlux}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedFlux<BinaryData> getAnomalyAlertingConfigurationsByAnomalyDetectionConfiguration(
            String configurationId, RequestOptions requestOptions) {
        return this.serviceClient.getAnomalyAlertingConfigurationsByAnomalyDetectionConfigurationAsync(
                configurationId, requestOptions);
    }

    /**
     * Create a new data source credential.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dataSourceCredentialId: String
     *     dataSourceCredentialName: String
     *     dataSourceCredentialDescription: String
     * }
     * }</pre>
     *
     * @param body Create data source credential request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> createCredentialWithResponse(BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.createCredentialWithResponseAsync(body, requestOptions);
    }

    /**
     * List all credentials.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             dataSourceCredentialId: String
     *             dataSourceCredentialName: String
     *             dataSourceCredentialDescription: String
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedFlux}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedFlux<BinaryData> listCredentials(RequestOptions requestOptions) {
        return this.serviceClient.listCredentialsAsync(requestOptions);
    }

    /**
     * Update a data source credential.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dataSourceCredentialName: String
     *     dataSourceCredentialDescription: String
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dataSourceCredentialId: String
     *     dataSourceCredentialName: String
     *     dataSourceCredentialDescription: String
     * }
     * }</pre>
     *
     * @param credentialId Data source credential unique ID.
     * @param body Update data source credential request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> updateCredentialWithResponse(
            String credentialId, BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.updateCredentialWithResponseAsync(credentialId, body, requestOptions);
    }

    /**
     * Delete a data source credential.
     *
     * @param credentialId Data source credential unique ID.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> deleteCredentialWithResponse(String credentialId, RequestOptions requestOptions) {
        return this.serviceClient.deleteCredentialWithResponseAsync(credentialId, requestOptions);
    }

    /**
     * Get a data source credential.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dataSourceCredentialId: String
     *     dataSourceCredentialName: String
     *     dataSourceCredentialDescription: String
     * }
     * }</pre>
     *
     * @param credentialId Data source credential unique ID.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return a data source credential along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> getCredentialWithResponse(String credentialId, RequestOptions requestOptions) {
        return this.serviceClient.getCredentialWithResponseAsync(credentialId, requestOptions);
    }

    /**
     * List all data feeds.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>dataFeedName</td><td>String</td><td>No</td><td>filter data feed by its name</td></tr>
     *     <tr><td>dataSourceType</td><td>String</td><td>No</td><td>filter data feed by its source type</td></tr>
     *     <tr><td>granularityName</td><td>String</td><td>No</td><td>filter data feed by its granularity</td></tr>
     *     <tr><td>status</td><td>String</td><td>No</td><td>filter data feed by its status</td></tr>
     *     <tr><td>creator</td><td>String</td><td>No</td><td>filter data feed by its creator</td></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             dataFeedId: String
     *             dataFeedName: String
     *             dataFeedDescription: String
     *             granularityName: String(Yearly/Monthly/Weekly/Daily/Hourly/Minutely/Custom)
     *             granularityAmount: Integer
     *             metrics: [
     *                 {
     *                     metricId: String
     *                     metricName: String
     *                     metricDisplayName: String
     *                     metricDescription: String
     *                 }
     *             ]
     *             dimension: [
     *                 {
     *                     dimensionName: String
     *                     dimensionDisplayName: String
     *                 }
     *             ]
     *             timestampColumn: String
     *             dataStartFrom: String
     *             startOffsetInSeconds: Long
     *             maxConcurrency: Integer
     *             minRetryIntervalInSeconds: Long
     *             stopRetryAfterInSeconds: Long
     *             needRollup: String(NoRollup/NeedRollup/AlreadyRollup)
     *             rollUpMethod: String(None/Sum/Max/Min/Avg/Count)
     *             rollUpColumns: [
     *                 String
     *             ]
     *             allUpIdentification: String
     *             fillMissingPointType: String(SmartFilling/PreviousValue/CustomValue/NoFilling)
     *             fillMissingPointValue: Double
     *             viewMode: String(Private/Public)
     *             admins: [
     *                 String
     *             ]
     *             viewers: [
     *                 String
     *             ]
     *             isAdmin: Boolean
     *             creator: String
     *             status: String(Active/Paused)
     *             createdTime: String
     *             actionLinkTemplate: String
     *             authenticationType: String(Basic/ManagedIdentity/AzureSQLConnectionString/DataLakeGen2SharedKey/ServicePrincipal/ServicePrincipalInKV)
     *             credentialId: String
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedFlux}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedFlux<BinaryData> listDataFeeds(RequestOptions requestOptions) {
        return this.serviceClient.listDataFeedsAsync(requestOptions);
    }

    /**
     * Create a new data feed.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dataFeedId: String
     *     dataFeedName: String
     *     dataFeedDescription: String
     *     granularityName: String(Yearly/Monthly/Weekly/Daily/Hourly/Minutely/Custom)
     *     granularityAmount: Integer
     *     metrics: [
     *         {
     *             metricId: String
     *             metricName: String
     *             metricDisplayName: String
     *             metricDescription: String
     *         }
     *     ]
     *     dimension: [
     *         {
     *             dimensionName: String
     *             dimensionDisplayName: String
     *         }
     *     ]
     *     timestampColumn: String
     *     dataStartFrom: String
     *     startOffsetInSeconds: Long
     *     maxConcurrency: Integer
     *     minRetryIntervalInSeconds: Long
     *     stopRetryAfterInSeconds: Long
     *     needRollup: String(NoRollup/NeedRollup/AlreadyRollup)
     *     rollUpMethod: String(None/Sum/Max/Min/Avg/Count)
     *     rollUpColumns: [
     *         String
     *     ]
     *     allUpIdentification: String
     *     fillMissingPointType: String(SmartFilling/PreviousValue/CustomValue/NoFilling)
     *     fillMissingPointValue: Double
     *     viewMode: String(Private/Public)
     *     admins: [
     *         String
     *     ]
     *     viewers: [
     *         String
     *     ]
     *     isAdmin: Boolean
     *     creator: String
     *     status: String(Active/Paused)
     *     createdTime: String
     *     actionLinkTemplate: String
     *     authenticationType: String(Basic/ManagedIdentity/AzureSQLConnectionString/DataLakeGen2SharedKey/ServicePrincipal/ServicePrincipalInKV)
     *     credentialId: String
     * }
     * }</pre>
     *
     * @param body parameters to create a data feed.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> createDataFeedWithResponse(BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.createDataFeedWithResponseAsync(body, requestOptions);
    }

    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<DataFeed> createDataFeed(DataFeed dataFeed) {
        return createDataFeedWithResponse(dataFeed).flatMap(FluxUtil::toMono);
    }

    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<DataFeed>> createDataFeedWithResponse(DataFeed dataFeed) {
        try {
            return withContext(context -> createDataFeedWithResponse(dataFeed, context));
        } catch (RuntimeException ex) {
            return monoError(logger, ex);
        }
    }

    Mono<Response<DataFeed>> createDataFeedWithResponse(DataFeed dataFeed, Context context) {
        Objects.requireNonNull(dataFeed, "'dataFeed' is required and cannot be null.");
        Objects.requireNonNull(dataFeed.getSource(), "'dataFeedSource' is required and cannot be null.");
        Objects.requireNonNull(dataFeed.getName(), "'dataFeedName' cannot be null or empty.");
        final DataFeedSchema dataFeedSchema = dataFeed.getSchema();
        final DataFeedGranularity dataFeedGranularity = dataFeed.getGranularity();
        final DataFeedIngestionSettings dataFeedIngestionSettings = dataFeed.getIngestionSettings();
        if (dataFeedSchema == null) {
            throw logger.logExceptionAsError(
                    new NullPointerException("'dataFeedSchema.metrics' cannot be null or empty."));
        } else {
            Objects.requireNonNull(dataFeedSchema.getMetrics(), "'dataFeedSchema.metrics' cannot be null or empty.");
        }
        if (dataFeedGranularity == null) {
            throw logger.logExceptionAsError(
                    new NullPointerException("'dataFeedGranularity.granularityType' is required and cannot be null."));
        } else {
            Objects.requireNonNull(
                    dataFeedGranularity.getGranularityType(), "'dataFeedGranularity.granularityType' is required.");
            if (CUSTOM.equals(dataFeedGranularity.getGranularityType())) {
                Objects.requireNonNull(
                        dataFeedGranularity.getCustomGranularityValue(),
                        "'dataFeedGranularity.customGranularityValue' is required when granularity type is CUSTOM");
            }
        }
        if (dataFeedIngestionSettings == null) {
            throw logger.logExceptionAsError(
                    new NullPointerException(
                            "'dataFeedIngestionSettings.ingestionStartTime' is required and cannot be null."));
        } else {
            Objects.requireNonNull(
                    dataFeedIngestionSettings.getIngestionStartTime(),
                    "'dataFeedIngestionSettings.ingestionStartTime' is required and cannot be null.");
        }
        final DataFeedOptions finalDataFeedOptions =
                dataFeed.getOptions() == null ? new DataFeedOptions() : dataFeed.getOptions();
        final DataFeedRollupSettings dataFeedRollupSettings =
                finalDataFeedOptions.getRollupSettings() == null
                        ? new DataFeedRollupSettings()
                        : finalDataFeedOptions.getRollupSettings();
        final DataFeedMissingDataPointFillSettings dataFeedMissingDataPointFillSettings =
                finalDataFeedOptions.getMissingDataPointFillSettings() == null
                        ? new DataFeedMissingDataPointFillSettings()
                        : finalDataFeedOptions.getMissingDataPointFillSettings();
//        final Context withTracing = context.addData(AZ_TRACING_NAMESPACE_KEY, METRICS_ADVISOR_TRACING_NAMESPACE_VALUE);
        DataFeedDetail dataFeedDetail =
                DataFeedTransforms.toDataFeedDetailSource(dataFeed.getSource())
                        .setDataFeedName(dataFeed.getName())
                        .setDataFeedDescription(finalDataFeedOptions.getDescription())
                        .setGranularityName(
                                Granularity.fromString(
                                        dataFeedGranularity.getGranularityType() == null
                                                ? null
                                                : dataFeedGranularity.getGranularityType().toString()))
                        .setGranularityAmount(dataFeedGranularity.getCustomGranularityValue())
                        .setDimension(DataFeedTransforms.toInnerDimensionsListForCreate(dataFeedSchema.getDimensions()))
                        .setMetrics(DataFeedTransforms.toInnerMetricsListForCreate(dataFeedSchema.getMetrics()))
                        .setTimestampColumn(dataFeedSchema.getTimestampColumn())
                        .setDataStartFrom(dataFeedIngestionSettings.getIngestionStartTime())
                        .setStartOffsetInSeconds(
                                dataFeedIngestionSettings.getIngestionStartOffset() == null
                                        ? null
                                        : dataFeedIngestionSettings.getIngestionStartOffset().getSeconds())
                        .setMaxConcurrency(dataFeedIngestionSettings.getDataSourceRequestConcurrency())
                        .setStopRetryAfterInSeconds(
                                dataFeedIngestionSettings.getStopRetryAfter() == null
                                        ? null
                                        : dataFeedIngestionSettings.getStopRetryAfter().getSeconds())
                        .setMinRetryIntervalInSeconds(
                                dataFeedIngestionSettings.getIngestionRetryDelay() == null
                                        ? null
                                        : dataFeedIngestionSettings.getIngestionRetryDelay().getSeconds())
                        .setRollUpColumns(dataFeedRollupSettings.getAutoRollupGroupByColumnNames())
                        .setRollUpMethod(
                                RollUpMethod.fromString(
                                        dataFeedRollupSettings.getDataFeedAutoRollUpMethod() == null
                                                ? null
                                                : dataFeedRollupSettings.getDataFeedAutoRollUpMethod().toString()))
                        .setNeedRollup(
                                NeedRollupEnum.fromString(
                                        dataFeedRollupSettings.getRollupType() == null
                                                ? null
                                                : dataFeedRollupSettings.getRollupType().toString()))
                        .setAllUpIdentification(dataFeedRollupSettings.getRollupIdentificationValue())
                        .setFillMissingPointType(
                                FillMissingPointType.fromString(
                                        dataFeedMissingDataPointFillSettings.getFillType() == null
                                                ? null
                                                : dataFeedMissingDataPointFillSettings.getFillType().toString()))
                        .setFillMissingPointValue(dataFeedMissingDataPointFillSettings.getCustomFillValue())
                        .setViewMode(
                                ViewMode.fromString(
                                        finalDataFeedOptions.getAccessMode() == null
                                                ? null
                                                : finalDataFeedOptions.getAccessMode().toString()))
                        .setViewers(finalDataFeedOptions.getViewers())
                        .setAdmins(finalDataFeedOptions.getAdmins())
                        .setActionLinkTemplate(finalDataFeedOptions.getActionLinkTemplate());
        BinaryData body = BinaryData.fromObject(dataFeedDetail);
        RequestOptions requestOptions = new RequestOptions();
        // requestOptions.setContext(withTracing);
        return this.createDataFeedWithResponse(body, requestOptions)
                .flatMap(
                        createDataFeedResponse -> {
                            final String dataFeedId =
                                    parseOperationId(createDataFeedResponse.getHeaders().getValue("Location"));
                            return getDataFeedWithResponse(dataFeedId);
                        });
    }


    /**
     * Get a data feed by its id.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dataFeedId: String
     *     dataFeedName: String
     *     dataFeedDescription: String
     *     granularityName: String(Yearly/Monthly/Weekly/Daily/Hourly/Minutely/Custom)
     *     granularityAmount: Integer
     *     metrics: [
     *         {
     *             metricId: String
     *             metricName: String
     *             metricDisplayName: String
     *             metricDescription: String
     *         }
     *     ]
     *     dimension: [
     *         {
     *             dimensionName: String
     *             dimensionDisplayName: String
     *         }
     *     ]
     *     timestampColumn: String
     *     dataStartFrom: String
     *     startOffsetInSeconds: Long
     *     maxConcurrency: Integer
     *     minRetryIntervalInSeconds: Long
     *     stopRetryAfterInSeconds: Long
     *     needRollup: String(NoRollup/NeedRollup/AlreadyRollup)
     *     rollUpMethod: String(None/Sum/Max/Min/Avg/Count)
     *     rollUpColumns: [
     *         String
     *     ]
     *     allUpIdentification: String
     *     fillMissingPointType: String(SmartFilling/PreviousValue/CustomValue/NoFilling)
     *     fillMissingPointValue: Double
     *     viewMode: String(Private/Public)
     *     admins: [
     *         String
     *     ]
     *     viewers: [
     *         String
     *     ]
     *     isAdmin: Boolean
     *     creator: String
     *     status: String(Active/Paused)
     *     createdTime: String
     *     actionLinkTemplate: String
     *     authenticationType: String(Basic/ManagedIdentity/AzureSQLConnectionString/DataLakeGen2SharedKey/ServicePrincipal/ServicePrincipalInKV)
     *     credentialId: String
     * }
     * }</pre>
     *
     * @param dataFeedId The data feed unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return a data feed by its id along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> getDataFeedByIdWithResponse(String dataFeedId, RequestOptions requestOptions) {
        return this.serviceClient.getDataFeedByIdWithResponseAsync(dataFeedId, requestOptions);
    }

    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<DataFeed>> getDataFeedWithResponse(String dataFeedId) {
        try {
            return withContext(context -> getDataFeedWithResponse(dataFeedId, context));
        } catch (RuntimeException ex) {
            return monoError(logger, ex);
        }
    }

    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<DataFeed> getDataFeed(String dataFeedId) {
        return getDataFeedWithResponse(dataFeedId).flatMap(FluxUtil::toMono);
    }

    Mono<Response<DataFeed>> getDataFeedWithResponse(String dataFeedId, Context context) {
        Objects.requireNonNull(dataFeedId, "'dataFeedId' cannot be null.");
        RequestOptions requestOptions = new RequestOptions();
        requestOptions.setContext(context);
        UUID.fromString(dataFeedId);
        return this.getDataFeedByIdWithResponse(dataFeedId, requestOptions)
                .map(
                        response -> {
                            DataFeedDetail dataFeedDetail = response.getValue().toObject(DataFeedDetail.class);
                            return new SimpleResponse<>(response, DataFeedTransforms.fromInner(dataFeedDetail));
                        });
    }

    /**
     * Update a data feed.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dataFeedName: String
     *     dataFeedDescription: String
     *     timestampColumn: String
     *     dataStartFrom: String
     *     startOffsetInSeconds: Long
     *     maxConcurrency: Integer
     *     minRetryIntervalInSeconds: Long
     *     stopRetryAfterInSeconds: Long
     *     needRollup: String(NoRollup/NeedRollup/AlreadyRollup)
     *     rollUpMethod: String(None/Sum/Max/Min/Avg/Count)
     *     rollUpColumns: [
     *         String
     *     ]
     *     allUpIdentification: String
     *     fillMissingPointType: String(SmartFilling/PreviousValue/CustomValue/NoFilling)
     *     fillMissingPointValue: Double
     *     viewMode: String(Private/Public)
     *     admins: [
     *         String
     *     ]
     *     viewers: [
     *         String
     *     ]
     *     status: String(Active/Paused)
     *     actionLinkTemplate: String
     *     authenticationType: String(Basic/ManagedIdentity/AzureSQLConnectionString/DataLakeGen2SharedKey/ServicePrincipal/ServicePrincipalInKV)
     *     credentialId: String
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dataFeedId: String
     *     dataFeedName: String
     *     dataFeedDescription: String
     *     granularityName: String(Yearly/Monthly/Weekly/Daily/Hourly/Minutely/Custom)
     *     granularityAmount: Integer
     *     metrics: [
     *         {
     *             metricId: String
     *             metricName: String
     *             metricDisplayName: String
     *             metricDescription: String
     *         }
     *     ]
     *     dimension: [
     *         {
     *             dimensionName: String
     *             dimensionDisplayName: String
     *         }
     *     ]
     *     timestampColumn: String
     *     dataStartFrom: String
     *     startOffsetInSeconds: Long
     *     maxConcurrency: Integer
     *     minRetryIntervalInSeconds: Long
     *     stopRetryAfterInSeconds: Long
     *     needRollup: String(NoRollup/NeedRollup/AlreadyRollup)
     *     rollUpMethod: String(None/Sum/Max/Min/Avg/Count)
     *     rollUpColumns: [
     *         String
     *     ]
     *     allUpIdentification: String
     *     fillMissingPointType: String(SmartFilling/PreviousValue/CustomValue/NoFilling)
     *     fillMissingPointValue: Double
     *     viewMode: String(Private/Public)
     *     admins: [
     *         String
     *     ]
     *     viewers: [
     *         String
     *     ]
     *     isAdmin: Boolean
     *     creator: String
     *     status: String(Active/Paused)
     *     createdTime: String
     *     actionLinkTemplate: String
     *     authenticationType: String(Basic/ManagedIdentity/AzureSQLConnectionString/DataLakeGen2SharedKey/ServicePrincipal/ServicePrincipalInKV)
     *     credentialId: String
     * }
     * }</pre>
     *
     * @param dataFeedId The data feed unique id.
     * @param body parameters to update a data feed.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> updateDataFeedWithResponse(
            String dataFeedId, BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.updateDataFeedWithResponseAsync(dataFeedId, body, requestOptions);
    }

    /**
     * Delete a data feed.
     *
     * @param dataFeedId The data feed unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> deleteDataFeedWithResponse(String dataFeedId, RequestOptions requestOptions) {
        return this.serviceClient.deleteDataFeedWithResponseAsync(dataFeedId, requestOptions);
    }

    /**
     * List all hooks.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>hookName</td><td>String</td><td>No</td><td>filter hook by its name</td></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             hookId: String
     *             hookName: String
     *             description: String
     *             externalLink: String
     *             admins: [
     *                 String
     *             ]
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedFlux}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedFlux<BinaryData> listHooks(RequestOptions requestOptions) {
        return this.serviceClient.listHooksAsync(requestOptions);
    }

    /**
     * Create a new hook.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     hookId: String
     *     hookName: String
     *     description: String
     *     externalLink: String
     *     admins: [
     *         String
     *     ]
     * }
     * }</pre>
     *
     * @param body Create hook request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> createHookWithResponse(BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.createHookWithResponseAsync(body, requestOptions);
    }

    /**
     * Get a hook by its id.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     hookId: String
     *     hookName: String
     *     description: String
     *     externalLink: String
     *     admins: [
     *         String
     *     ]
     * }
     * }</pre>
     *
     * @param hookId Hook unique ID.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return a hook by its id along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> getHookWithResponse(String hookId, RequestOptions requestOptions) {
        return this.serviceClient.getHookWithResponseAsync(hookId, requestOptions);
    }

    /**
     * Update a hook.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     hookName: String
     *     description: String
     *     externalLink: String
     *     admins: [
     *         String
     *     ]
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     hookId: String
     *     hookName: String
     *     description: String
     *     externalLink: String
     *     admins: [
     *         String
     *     ]
     * }
     * }</pre>
     *
     * @param hookId Hook unique ID.
     * @param body Update hook request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> updateHookWithResponse(
            String hookId, BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.updateHookWithResponseAsync(hookId, body, requestOptions);
    }

    /**
     * Delete a hook.
     *
     * @param hookId Hook unique ID.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> deleteHookWithResponse(String hookId, RequestOptions requestOptions) {
        return this.serviceClient.deleteHookWithResponseAsync(hookId, requestOptions);
    }

    /**
     * Get data ingestion status by data feed.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             timestamp: String
     *             status: String(NotStarted/Scheduled/Running/Succeeded/Failed/NoData/Error/Paused)
     *             message: String
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param dataFeedId The data feed unique id.
     * @param body The query time range.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return data ingestion status by data feed as paginated response with {@link PagedFlux}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedFlux<BinaryData> getDataFeedIngestionStatus(
            String dataFeedId, BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.getDataFeedIngestionStatusAsync(dataFeedId, body, requestOptions);
    }

    /**
     * Reset data ingestion status by data feed to backfill data.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     * }
     * }</pre>
     *
     * @param dataFeedId The data feed unique id.
     * @param body The backfill time range.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> resetDataFeedIngestionStatusWithResponse(
            String dataFeedId, BinaryData body, RequestOptions requestOptions) {
        return this.serviceClient.resetDataFeedIngestionStatusWithResponseAsync(dataFeedId, body, requestOptions);
    }

    /**
     * Get data last success ingestion job timestamp by data feed.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     latestSuccessTimestamp: String
     *     latestActiveTimestamp: String
     * }
     * }</pre>
     *
     * @param dataFeedId The data feed unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return data last success ingestion job timestamp by data feed along with {@link Response} on successful
     *     completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> getIngestionProgressWithResponse(
            String dataFeedId, RequestOptions requestOptions) {
        return this.serviceClient.getIngestionProgressWithResponseAsync(dataFeedId, requestOptions);
    }

    /**
     * List all anomaly detection configurations for specific metric.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     value: [
     *         {
     *             anomalyDetectionConfigurationId: String
     *             name: String
     *             description: String
     *             metricId: String
     *             wholeMetricConfiguration: {
     *                 conditionOperator: String(AND/OR)
     *                 smartDetectionCondition: {
     *                     sensitivity: double
     *                     anomalyDetectorDirection: String(Both/Down/Up)
     *                     suppressCondition: {
     *                         minNumber: int
     *                         minRatio: double
     *                     }
     *                 }
     *                 hardThresholdCondition: {
     *                     lowerBound: Double
     *                     upperBound: Double
     *                     anomalyDetectorDirection: String(Both/Down/Up)
     *                     suppressCondition: (recursive schema, see suppressCondition above)
     *                 }
     *                 changeThresholdCondition: {
     *                     changePercentage: double
     *                     shiftPoint: int
     *                     withinRange: boolean
     *                     anomalyDetectorDirection: String(Both/Down/Up)
     *                     suppressCondition: (recursive schema, see suppressCondition above)
     *                 }
     *             }
     *             dimensionGroupOverrideConfigurations: [
     *                 {
     *                     group: {
     *                         dimension: {
     *                             String: String
     *                         }
     *                     }
     *                     conditionOperator: String(AND/OR)
     *                     smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *                     hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *                     changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *                 }
     *             ]
     *             seriesOverrideConfigurations: [
     *                 {
     *                     series: {
     *                         dimension: {
     *                             String: String
     *                         }
     *                     }
     *                     conditionOperator: String(AND/OR)
     *                     smartDetectionCondition: (recursive schema, see smartDetectionCondition above)
     *                     hardThresholdCondition: (recursive schema, see hardThresholdCondition above)
     *                     changeThresholdCondition: (recursive schema, see changeThresholdCondition above)
     *                 }
     *             ]
     *         }
     *     ]
     *     nextLink: String
     * }
     * }</pre>
     *
     * @param metricId metric unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedFlux}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedFlux<BinaryData> getAnomalyDetectionConfigurationsByMetric(
            String metricId, RequestOptions requestOptions) {
        return this.serviceClient.getAnomalyDetectionConfigurationsByMetricAsync(metricId, requestOptions);
    }
}
