// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.metricsadvisor;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;

/** Initializes a new instance of the synchronous MetricsAdvisorClient type. */
@ServiceClient(builder = MetricsAdvisorClientBuilder.class)
public final class MetricsAdvisorClient {
    @Generated private final MetricsAdvisorAsyncClient client;

    /**
     * Initializes an instance of MetricsAdvisorClient class.
     *
     * @param client the async client.
     */
    @Generated
    MetricsAdvisorClient(MetricsAdvisorAsyncClient client) {
        this.client = client;
    }

    /**
     * Get latest usage stats.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     timestamp: String
     *     activeSeriesCount: Integer
     *     allSeriesCount: Integer
     *     metricsCount: Integer
     *     dataFeedCount: Integer
     * }
     * }</pre>
     *
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return latest usage stats along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getActiveSeriesCountWithResponse(RequestOptions requestOptions) {
        return this.client.getActiveSeriesCountWithResponse(requestOptions).block();
    }

    /**
     * Query a single anomaly alerting configuration.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     anomalyAlertingConfigurationId: String
     *     name: String
     *     description: String
     *     crossMetricsOperator: String(AND/OR/XOR)
     *     splitAlertByDimensions: [
     *         String
     *     ]
     *     hookIds: [
     *         String
     *     ]
     *     metricAlertingConfigurations: [
     *         {
     *             anomalyDetectionConfigurationId: String
     *             anomalyScopeType: String(All/Dimension/TopN)
     *             negationOperation: Boolean
     *             dimensionAnomalyScope: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             topNAnomalyScope: {
     *                 top: int
     *                 period: int
     *                 minTopCount: int
     *             }
     *             severityFilter: {
     *                 minAlertSeverity: String(Low/Medium/High)
     *                 maxAlertSeverity: String(Low/Medium/High)
     *             }
     *             snoozeFilter: {
     *                 autoSnooze: int
     *                 snoozeScope: String(Metric/Series)
     *                 onlyForSuccessive: boolean
     *             }
     *             valueFilter: {
     *                 lower: Double
     *                 upper: Double
     *                 direction: String(Both/Down/Up)
     *                 type: String(Value/Mean)
     *                 metricId: String
     *                 triggerForMissing: Boolean
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly alerting configuration unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getAnomalyAlertingConfigurationWithResponse(
            String configurationId, RequestOptions requestOptions) {
        return this.client.getAnomalyAlertingConfigurationWithResponse(configurationId, requestOptions).block();
    }

    /**
     * Query alerts under anomaly alerting configuration.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     *     timeMode: String(AnomalyTime/CreatedTime/ModifiedTime)
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             alertId: String
     *             timestamp: String
     *             createdTime: String
     *             modifiedTime: String
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly alerting configuration unique id.
     * @param body query alerting result request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getAlertsByAnomalyAlertingConfiguration(
            String configurationId, BinaryData body, RequestOptions requestOptions) {
        return new PagedIterable<>(
                this.client.getAlertsByAnomalyAlertingConfiguration(configurationId, body, requestOptions));
    }

    /**
     * Query anomalies under a specific alert.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             dataFeedId: String
     *             metricId: String
     *             anomalyDetectionConfigurationId: String
     *             timestamp: String
     *             createdTime: String
     *             modifiedTime: String
     *             dimension: {
     *                 String: String
     *             }
     *             property: {
     *                 anomalySeverity: String(Low/Medium/High)
     *                 anomalyStatus: String(Active/Resolved)
     *                 value: Double
     *                 expectedValue: Double
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly alerting configuration unique id.
     * @param alertId alert id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getAnomaliesFromAlertByAnomalyAlertingConfiguration(
            String configurationId, String alertId, RequestOptions requestOptions) {
        return new PagedIterable<>(
                this.client.getAnomaliesFromAlertByAnomalyAlertingConfiguration(
                        configurationId, alertId, requestOptions));
    }

    /**
     * Query incidents under a specific alert.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             dataFeedId: String
     *             metricId: String
     *             anomalyDetectionConfigurationId: String
     *             incidentId: String
     *             startTime: String
     *             lastTime: String
     *             rootNode: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             property: {
     *                 maxSeverity: String(Low/Medium/High)
     *                 incidentStatus: String(Active/Resolved)
     *                 valueOfRootNode: Double
     *                 expectedValueOfRootNode: Double
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly alerting configuration unique id.
     * @param alertId alert id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getIncidentsFromAlertByAnomalyAlertingConfiguration(
            String configurationId, String alertId, RequestOptions requestOptions) {
        return new PagedIterable<>(
                this.client.getIncidentsFromAlertByAnomalyAlertingConfiguration(
                        configurationId, alertId, requestOptions));
    }

    /**
     * Query series enriched by anomaly detection.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     *     series: [
     *         {
     *             dimension: {
     *                 String: String
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     value: [
     *         {
     *             series: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             timestampList: [
     *                 String
     *             ]
     *             valueList: [
     *                 double
     *             ]
     *             isAnomalyList: [
     *                 boolean
     *             ]
     *             periodList: [
     *                 int
     *             ]
     *             expectedValueList: [
     *                 double
     *             ]
     *             lowerBoundaryList: [
     *                 double
     *             ]
     *             upperBoundaryList: [
     *                 double
     *             ]
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param body query series detection result request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getSeriesByAnomalyDetectionConfigurationWithResponse(
            String configurationId, BinaryData body, RequestOptions requestOptions) {
        return this.client
                .getSeriesByAnomalyDetectionConfigurationWithResponse(configurationId, body, requestOptions)
                .block();
    }

    /**
     * Query anomalies under anomaly detection configuration.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     *     filter: {
     *         dimensionFilter: [
     *             {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *         ]
     *         severityFilter: {
     *             min: String(Low/Medium/High)
     *             max: String(Low/Medium/High)
     *         }
     *     }
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             dataFeedId: String
     *             metricId: String
     *             anomalyDetectionConfigurationId: String
     *             timestamp: String
     *             createdTime: String
     *             modifiedTime: String
     *             dimension: {
     *                 String: String
     *             }
     *             property: {
     *                 anomalySeverity: String(Low/Medium/High)
     *                 anomalyStatus: String(Active/Resolved)
     *                 value: Double
     *                 expectedValue: Double
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param body query detection anomaly result request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getAnomaliesByAnomalyDetectionConfiguration(
            String configurationId, BinaryData body, RequestOptions requestOptions) {
        return new PagedIterable<>(
                this.client.getAnomaliesByAnomalyDetectionConfiguration(configurationId, body, requestOptions));
    }

    /**
     * Query dimension values of anomalies.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     *     dimensionName: String
     *     dimensionFilter: {
     *         dimension: {
     *             String: String
     *         }
     *     }
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         String
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param body query dimension values request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getDimensionOfAnomaliesByAnomalyDetectionConfiguration(
            String configurationId, BinaryData body, RequestOptions requestOptions) {
        return new PagedIterable<>(
                this.client.getDimensionOfAnomaliesByAnomalyDetectionConfiguration(
                        configurationId, body, requestOptions));
    }

    /**
     * Query incidents under anomaly detection configuration.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     *     filter: {
     *         dimensionFilter: [
     *             {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *         ]
     *     }
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             dataFeedId: String
     *             metricId: String
     *             anomalyDetectionConfigurationId: String
     *             incidentId: String
     *             startTime: String
     *             lastTime: String
     *             rootNode: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             property: {
     *                 maxSeverity: String(Low/Medium/High)
     *                 incidentStatus: String(Active/Resolved)
     *                 valueOfRootNode: Double
     *                 expectedValueOfRootNode: Double
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param body query detection incident result request.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getIncidentsByAnomalyDetectionConfiguration(
            String configurationId, BinaryData body, RequestOptions requestOptions) {
        return new PagedIterable<>(
                this.client.getIncidentsByAnomalyDetectionConfiguration(configurationId, body, requestOptions));
    }

    /**
     * Query incidents under anomaly detection configuration.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     *     <tr><td>$token</td><td>String</td><td>No</td><td>the token for getting the next page</td></tr>
     * </table>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             dataFeedId: String
     *             metricId: String
     *             anomalyDetectionConfigurationId: String
     *             incidentId: String
     *             startTime: String
     *             lastTime: String
     *             rootNode: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             property: {
     *                 maxSeverity: String(Low/Medium/High)
     *                 incidentStatus: String(Active/Resolved)
     *                 valueOfRootNode: Double
     *                 expectedValueOfRootNode: Double
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getIncidentsByAnomalyDetectionConfigurationNextPages(
            String configurationId, RequestOptions requestOptions) {
        return new PagedIterable<>(
                this.client.getIncidentsByAnomalyDetectionConfigurationNextPages(configurationId, requestOptions));
    }

    /**
     * Query root cause for incident.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     value: [
     *         {
     *             rootCause: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             path: [
     *                 String
     *             ]
     *             score: double
     *             description: String
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param configurationId anomaly detection configuration unique id.
     * @param incidentId incident id.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getRootCauseOfIncidentByAnomalyDetectionConfigurationWithResponse(
            String configurationId, String incidentId, RequestOptions requestOptions) {
        return this.client
                .getRootCauseOfIncidentByAnomalyDetectionConfigurationWithResponse(
                        configurationId, incidentId, requestOptions)
                .block();
    }

    /**
     * Get a metric feedback by its id.
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     feedbackId: String
     *     createdTime: String
     *     userPrincipal: String
     *     metricId: String
     *     dimensionFilter: {
     *         dimension: {
     *             String: String
     *         }
     *     }
     * }
     * }</pre>
     *
     * @param feedbackId the unique feedback ID.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return a metric feedback by its id along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getMetricFeedbackWithResponse(String feedbackId, RequestOptions requestOptions) {
        return this.client.getMetricFeedbackWithResponse(feedbackId, requestOptions).block();
    }

    /**
     * List feedback on the given metric.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     metricId: String
     *     dimensionFilter: {
     *         dimension: {
     *             String: String
     *         }
     *     }
     *     feedbackType: String(Anomaly/ChangePoint/Period/Comment)
     *     startTime: String
     *     endTime: String
     *     timeMode: String(MetricTimestamp/FeedbackCreatedTime)
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             feedbackId: String
     *             createdTime: String
     *             userPrincipal: String
     *             metricId: String
     *             dimensionFilter: {
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param body metric feedback filter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> listMetricFeedbacks(BinaryData body, RequestOptions requestOptions) {
        return new PagedIterable<>(this.client.listMetricFeedbacks(body, requestOptions));
    }

    /**
     * Create a new metric feedback.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     feedbackId: String
     *     createdTime: String
     *     userPrincipal: String
     *     metricId: String
     *     dimensionFilter: {
     *         dimension: {
     *             String: String
     *         }
     *     }
     * }
     * }</pre>
     *
     * @param body metric feedback.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> createMetricFeedbackWithResponse(BinaryData body, RequestOptions requestOptions) {
        return this.client.createMetricFeedbackWithResponse(body, requestOptions).block();
    }

    /**
     * Get time series data from metric.
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     *     series: [
     *         {
     *             String: String
     *         }
     *     ]
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     value: [
     *         {
     *             id: {
     *                 metricId: String
     *                 dimension: {
     *                     String: String
     *                 }
     *             }
     *             timestampList: [
     *                 String
     *             ]
     *             valueList: [
     *                 double
     *             ]
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param metricId metric unique id.
     * @param body query time series data condition.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return time series data from metric along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getMetricDataWithResponse(
            String metricId, BinaryData body, RequestOptions requestOptions) {
        return this.client.getMetricDataWithResponse(metricId, body, requestOptions).block();
    }

    /**
     * List series (dimension combinations) from metric.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     activeSince: String
     *     dimensionFilter: {
     *         String: [
     *             String
     *         ]
     *     }
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             metricId: String
     *             dimension: {
     *                 String: String
     *             }
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param metricId metric unique id.
     * @param body filter to query series.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getMetricSeries(String metricId, BinaryData body, RequestOptions requestOptions) {
        return new PagedIterable<>(this.client.getMetricSeries(metricId, body, requestOptions));
    }

    /**
     * List dimension from certain metric.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     dimensionName: String
     *     dimensionValueFilter: String
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         String
     *     ]
     * }
     * }</pre>
     *
     * @param metricId metric unique id.
     * @param body query dimension option.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getMetricDimension(
            String metricId, BinaryData body, RequestOptions requestOptions) {
        return new PagedIterable<>(this.client.getMetricDimension(metricId, body, requestOptions));
    }

    /**
     * Query anomaly detection status.
     *
     * <p><strong>Query Parameters</strong>
     *
     * <table border="1">
     *     <caption>Query Parameters</caption>
     *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     *     <tr><td>$skip</td><td>String</td><td>No</td><td>for paging, skipped number</td></tr>
     *     <tr><td>$maxpagesize</td><td>String</td><td>No</td><td>the maximum number of items in one page</td></tr>
     * </table>
     *
     * <p><strong>Request Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     startTime: String
     *     endTime: String
     * }
     * }</pre>
     *
     * <p><strong>Response Body Schema</strong>
     *
     * <pre>{@code
     * {
     *     nextLink: String
     *     value: [
     *         {
     *             timestamp: String
     *             status: String
     *             message: String
     *         }
     *     ]
     * }
     * }</pre>
     *
     * @param metricId metric unique id.
     * @param body query options.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> getEnrichmentStatusByMetric(
            String metricId, BinaryData body, RequestOptions requestOptions) {
        return new PagedIterable<>(this.client.getEnrichmentStatusByMetric(metricId, body, requestOptions));
    }
}
